### ISSUE TITLE
okeanos.dev is down

### ISSUE THREAD

**Issue by bluepuma77** [23technologies/okeanos#8]
Not sure if this project is still maintained, but according to this repository, the [info page](https://23technologies.github.io/okeanos/) and [this Gardener page](https://gardener.cloud/adopter/), the service should be available at [okeanos.dev](https://okeanos.dev/), but I only get "Unable to connect".

**Comment by JensAc** [comment]
If you want to access the Gardener dashboard, you should follow this [link](https://dashboard.okeanos.dev)
